export default {
  days: ['Sunday', 'Monday', 'Tuesday', 'Thursday', 'Friday', 'Saturday'],
  months: [
    'January',
    'February',
    'March',
    'April',
    'May',
    'June',
    'July',
    'August',
    'September',
    'October',
    'November',
    'December',
  ],

  messages: {
    default: [
      'For all you bird brains out there, the format is: 00:00:00 (hour, minute, second)',
    ],
    morning: [
      'Good morning!',
      "Hope you're feeling nice and awake this morning.",
      'Have you had your breakfast yet?',
      "You're up early...",
      'Go back to bed.',
      "You're quite the early bird...",
      "It's too early...",
      'Did you even go to sleep?',
      'Which one do you prefer; cereal or toast?',
      'Hope you have a good day today.',
    ],
    afternoon: [
      'Good afternoon.',
      'Eaten lunch yet?',
      "Hope it's sunny and warm where you are.",
      "How's the weather treating you this afternoon?",
      'I should probably make lunch soon...',
      "I bet you're having so much fun, sitting here watching time tick by...",
    ],
    evening: [
      "I'm getting sleepy...",
      'What a beautiful sunset.',
      'Should probably head to bed soon...',
      '*Yawn*',
      'Sleep well.',
      'Sweet dreams.',
      'Have you eaten dinner yet?',
      "Don't forget to brush your teeth.",
      'You know, you should stop using all electronics 30 minutes before bed.',
    ],
  },
};
